var dishes = {
    soup: [],
    pizza: [
        { name: 'PIZZA QUATRO STAHIONI', description: 'Integer ullamcorper neque eu purus euismod', price: 55.68},
        { name: 'PIZZA QUATRO STAHIONI', description: 'Integer ullamcorper neque eu purus euismod', price: 55.68},
        { name: 'PIZZA QUATRO STAHIONI', description: 'Integer ullamcorper neque eu purus euismod', price: 55.68},
        { name: 'PIZZA QUATRO STAHIONI', description: 'Integer ullamcorper neque eu purus euismod', price: 55.68},
        { name: 'PIZZA QUATRO STAHIONI', description: 'Integer ullamcorper neque eu purus euismod', price: 55.68},
        { name: 'PIZZA QUATRO STAHIONI', description: 'Integer ullamcorper neque eu purus euismod', price: 55.68},
        { name: 'PIZZA QUATRO STAHIONI', description: 'Integer ullamcorper neque eu purus euismod', price: 55.68},
        { name: 'PIZZA QUATRO STAHIONI', description: 'Integer ullamcorper neque eu purus euismod', price: 55.68},
        { name: 'PIZZA QUATRO STAHIONI', description: 'Integer ullamcorper neque eu purus euismod', price: 55.68},
        { name: 'PIZZA QUATRO STAHIONI', description: 'Integer ullamcorper neque eu purus euismod', price: 55.68},
        { name: 'PIZZA QUATRO STAHIONI', description: 'Integer ullamcorper neque eu purus euismod', price: 55.68},
        { name: 'PIZZA QUATRO STAHIONI', description: 'Integer ullamcorper neque eu purus euismod', price: 55.68},
        { name: 'PIZZA QUATRO STAHIONI', description: 'Integer ullamcorper neque eu purus euismod', price: 55.68},
        { name: 'PIZZA QUATRO STAHIONI', description: 'Integer ullamcorper neque eu purus euismod', price: 55.68},
        { name: 'PIZZA QUATRO STAHIONI', description: 'Integer ullamcorper neque eu purus euismod', price: 55.68},
        { name: 'PIZZA QUATRO STAHIONI', description: 'Integer ullamcorper neque eu purus euismod', price: 55.68},
        { name: 'PIZZA QUATRO STAHIONI', description: 'Integer ullamcorper neque eu purus euismod', price: 55.68},
        { name: 'PIZZA QUATRO STAHIONI', description: 'Integer ullamcorper neque eu purus euismod', price: 55.68},
        { name: 'PIZZA QUATRO STAHIONI', description: 'Integer ullamcorper neque eu purus euismod', price: 55.68},
        { name: 'PIZZA QUATRO STAHIONI', description: 'Integer ullamcorper neque eu purus euismod', price: 55.68},
        { name: 'PIZZA QUATRO STAHIONI', description: 'Integer ullamcorper neque eu purus euismod', price: 55.68},
    ],
    pasta: [
        {name: 'PASTA QUATRO STAHIONI', description: 'Integer ullamcorper neque LOL eu purus euismod', price: 77.68},
        {name: 'PASTA QUATRO STAHIONI', description: 'Integer ullamcorper neque LOL eu purus euismod', price: 77.68},
        {name: 'PASTA QUATRO STAHIONI', description: 'Integer', price: 77.68},
        {name: 'PASTA QUATRO STAHIONI', description: 'Integer ullamcorper neque LOL eu purus euismod', price: 77.68},
        {name: 'PASTA QUATRO STAHIONI', description: 'Integer ullamcorper neque LOL eu purus euismod', price: 77.68},
        {name: 'PASTA QUATRO STAHIONI', description: 'Integer ullamcorper neque LOL eu purus euismod', price: 77.68},
        {name: 'PASTA QUATRO STAHIONI', description: 'Integer ullamcorper neque LOL eu purus euismod', price: 77.68},
        {name: 'PASTA QUATRO STAHIONI', description: 'Integer ullamcorper neque LOL eu purus euismod', price: 77.68},
        {name: 'PASTA QUATRO STAHIONI', description: 'Integer ullamcorper neque LOL eu purus euismod', price: 77.68},
        {name: 'PASTA QUATRO STAHIONI', description: 'Integer ullamcorper neque LOL eu purus euismod', price: 77.68},
        {name: 'PASTA QUATRO STAHIONI', description: 'Integer ullamcorper neque LOL eu purus euismod', price: 77.68},
        {name: 'PASTA QUATRO STAHIONI', description: 'Integer ullamcorper neque LOL eu purus euismod', price: 77.68},
        {name: 'PASTA QUATRO STAHIONI', description: 'Integer ullamcorper neqod', price: 77.68},
        {name: 'PASTA QUATRO STAHIONI', description: 'Integer ullamcorper neque LOL eu purus euismod', price: 77.68},
        {name: 'PASTA QUATRO STAHIONI', description: 'Integer ullamcorper neque LOL eu purus euismod', price: 77.68},


    ],
    desert: [
        {name: 'PASTA QUATRO STAHIONI PASTA QUATRO STAHIONI', description: 'Integer ullamcorper neque LOL eu purus euismod', price: 77.68},
        {name: 'PASTA QUATRO STAHIONI PASTA QUATRO STAHIONI', description: 'Integer ullamcorper neque LOL eu purus euismod', price: 77.68},
    ],
    wine: [
        {name: 'BEST WINE EVER', description: 'NO WORDS', price: 100},
        {name: 'BEST WINE EVER', description: 'NO WORDS', price: 100},
    
], 
    drinks: []
}